name: Test & Build Package

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/*"]
    name: Test on node@v${{ matrix.node }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4
      - name: Setup node 🔧
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: "pnpm"
      - name: Install 🪄
        run: pnpm install --frozen-lockfile
      - name: Lint 🔍
        run: pnpm run lint
      - name: TypeScript 🔍
        run: pnpm run check
      - name: Test 🔍
        run: pnpm run test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/*"]
    name: Build on node@v${{ matrix.node }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4
      - name: Setup node 🔧
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: "pnpm"
      - name: Install 🪄
        run: pnpm install --frozen-lockfile
      - name: Build 💎
        run: pnpm run build
